CREATE DATABASE Library;

USE Library;

CREATE TABLE Books(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(200) NOT NULL,
	Author NVARCHAR(200) NOT NULL,
	Publisher NVARCHAR(200) NOT NULL,
	Year INT,
	UserId INT,
);

CREATE TABLE Users(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(200) NOT NULL,
	Age INT
);


